### ISSUE TITLE
Local IP

### ISSUE THREAD

**Issue by basimolimajeed** [sandervandevelde/Advantech.Wise4012e.Modbus.Simulation#1]
Hi
The instruction Go to 'settings.json' and replace the localhost address by your specific local IP Address (you can look it up using 'ipconfig') suggests that you can only interact with this module if it is installed on the IoT edge device (local IP) or in same network?

**Comment by sandervandevelde** [comment]
Yes. if the firewall of another machine does not prevent calls to your simulation, you can run it there. A successful ping is to your simulation machine is a good indication.

**Comment by basimolimajeed** [comment]
Perfect thanks
    On Wednesday, 4 July 2018, 22:39:03 BST, Sander van de Velde <notifications@github.com> wrote:  
 
 
Yes. if the firewall of another machine does not prevent calls to your simulation, you can run it there. A successful ping is to your simulation machine is a good indication.
